version: '3.1'

services:
  measurementapp:
    image: webdevops/php-apache:7.4
    restart: always
    environment:
      PHP_DISPLAY_ERRORS: 1
    ports:
      - 82:80
    volumes:
      - ./appcode:/app